"""Reason template loader.

Reads reason_templates.json (generated by scripts/generate_reason_templates.py)
and returns a dict of reason_code -> {headline, subtext} templates.

Falls back to empty dict if the file is missing; callers use the
hardcoded strings in the engine in that case. This is deliberate: the
app must still work if the build-time step hasn't been run yet.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)


def load_reason_templates(path: str | Path) -> dict[str, dict[str, str]]:
    """Load the Gemini-generated templates file.

    Returns an empty dict on any load error. The engine falls back
    gracefully to hardcoded strings in that case.
    """
    templates_path = Path(path)
    if not templates_path.exists():
        logger.info("Reason templates file not found at %s; using hardcoded strings", path)
        return {}

    try:
        with templates_path.open(encoding="utf-8") as fh:
            payload = json.load(fh)
        templates = payload.get("templates", {})
        if not isinstance(templates, dict):
            logger.warning("Reason templates payload malformed; ignoring")
            return {}
        return {code: data for code, data in templates.items() if isinstance(data, dict)}
    except (json.JSONDecodeError, OSError) as exc:
        logger.warning("Failed to load reason templates: %s", exc)
        return {}
